### ISSUE TITLE
Llittlefs on sd-driver

### ISSUE THREAD

**Issue by OscarGarciaF** [ARMmbed/sd-driver#101]
does sd-driver  support littlefs?
I have tried using it with File and FILE and it does no seems to work.
Also stat() seems to always fail.

Is there some special way to accomplish this?

**Comment by geky** [comment]
Yes is should work!

Have you tried starting with our filesystem example as a baseline?
https://github.com/armmbed/mbed-os-example-filesystem

Were you able to use the FAT filesystem on the SD card? Do you know if there might be hardware problems?

One thing to note, FAT and littlefs are inherently different filesystems on the SD card, so you do need to reformat the SD card in order to switch between the two.

If you're using logic that trys to mount, and falls back to format, it's possible formatting one filesystem corrupted the other in a way that mount can't detect. You can try calling littlefs's format directly before using the SD card. (We have a fix for this in mbed-os-5.9, but it hasn't been released quite yet).

**Comment by OscarGarciaF** [comment]
it worked on the FAT, i will try formatting to see if it works

**Comment by OscarGarciaF** [comment]
format (i have tried calling it before mount) and .mount both hang and never return a value

**Comment by geky** [comment]
That's unfortunate. Some questions:
- What board are you using?
- What mbed-os version? (`git log`)
- What sd-driver version? (`git log`)
- Are you able to share any code that shows the issue?

I'm not aware of any issues with SD and littlefs, I'm not sure what the issue could be.

**Comment by JanneKiiskila** [comment]
It definitely should work, it works with the Mbed Cloud Client.
