### ISSUE TITLE
Update README.md - version at least

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/sd-driver#34]
Seems significant changes were done lately, please update at least the version in the REAMDE.md.

@geky  @deepikabhavnani

**Comment by geky** [comment]
It looks like the version hasn't been updated in a while. I went ahead and jumped to version 0.1.0. Since a few features were added I figure we can give the current version some time to work through bugs before jumping to 1.0.0.

version 0.1.0:
https://github.com/ARMmbed/sd-driver/releases/tag/sd-driver-0.1.0-mbed-os-5.5.1
